import type { Metadata } from "next";
import { CTA, FAQSection, ImagePlaceholder, InternalLinks } from "@/components/Sections";
import { JsonLd } from "@/components/JsonLd";
import { siteUrl, whatsappUrl } from "@/lib/site";

export const metadata: Metadata = { title: "Contatti BluOrtensia | Proposta ombrelloni artigianali", description: "Invia una foto del tuo outdoor a BluOrtensia e ricevi una proposta per teli artigianali o ombrelloni completi per hospitality e ville.", alternates: { canonical: "/contatti" } };

export default function Contatti() {
  const contact = { "@context":"https://schema.org", "@type":"ContactPage", url: `${siteUrl}/contatti`, name:"Contatti BluOrtensia", mainEntity:{"@type":"Organization", name:"BluOrtensia", contactPoint:{"@type":"ContactPoint", contactType:"customer service", url: whatsappUrl}} };
  return <main><JsonLd data={contact}/><section className="container-pad grid items-center gap-12 py-16 md:py-24 lg:grid-cols-[0.95fr_1.05fr]"><div className="hero-copy"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.3em] text-sage">Contatti</p><h1 className="heading max-w-5xl text-5xl leading-tight md:text-7xl">Mandaci una foto del tuo spazio outdoor</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-ink/75">Da una foto possiamo capire luce, proporzioni, materiali e atmosfera. Ti suggeriamo modello, colore e soluzione più adatta: telo artigianale per struttura esistente o ombrellone completo.</p><div className="mt-8"><CTA label="Invia una foto del tuo outdoor" /></div></div><ImagePlaceholder label="foto outdoor" title="Da qui nasce la proposta" text="Carica o invia su WhatsApp una vista d'insieme, un dettaglio della struttura e le misure indicative. Più il contesto è chiaro, più la proposta sarà precisa." /></section><section className="container-pad reveal py-20"><div className="card p-8 md:p-12"><h2 className="heading text-4xl md:text-5xl">Cosa inviarci su WhatsApp</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><p className="rounded-3xl bg-sand/15 p-6 leading-7">Una foto ampia dello spazio: spiaggia, piscina, terrazza, giardino o dehors.</p><p className="rounded-3xl bg-sage/15 p-6 leading-7">Diametro, altezza, quantità e foto della struttura se già presente.</p><p className="rounded-3xl bg-soft-blue/15 p-6 leading-7">Colori desiderati, tempi, uso previsto e tipo di atmosfera che vuoi ottenere.</p></div></div></section><section className="container-pad reveal py-20"><h2 className="heading text-4xl md:text-5xl">Pagine correlate</h2><div className="mt-8"><InternalLinks /></div></section><FAQSection /></main>;
}
